### ISSUE TITLE
Downloading SARS-CoV-2 Variation Data fails in dataprep/01c-CNCBVariant.ipynb notebook

### ISSUE THREAD

**Issue by shophine** [covid-19-net/covid-19-community#319]
It throws 'error_prem: 550 Failed to change directory' while downloading and caching data files with variant information. Can you please upload the data itself to the repository if possible?

**Comment by pwrose** [comment]
The variant information is downloaded incrementally daily into the cache directory (on our server) with this script:
https://github.com/covid-19-net/covid-19-community/blob/master/scripts/download.sh (note, there is a single file for each strain, so currently there are about 1 million files!)

However, the download of these data currently fails (see #321) since CNCB is reorganizing their data. I'm in contact with CNCB to resolve this issue.

**Comment by pwrose** [comment]
The CNCB ftp site is back up. The download.sh script should work again.
