### ISSUE TITLE
Neo4j database shutdown

### ISSUE THREAD

**Issue by pwrose** [covid-19-net/covid-19-community#6]
In the following notebook https://github.com/covid-19-net/covid-19-community/blob/master/notebooks/3-ExampleQueries.ipynb we stop the Neo4j database at the end.

Often, the shutdown fails.

Does anyone know what causes this issue and how to shut down cleanly?

**Comment by MarkPAndrews** [comment]
Typical the shutdown will fail because the server is busy doing something else.  It will try for 120 seconds and then give up.  You can force it to stop by issuing a `kill -9` but that's not very "clean" depending on why you are shutting the server down.  The cleanest why is to keep trying "neo4j stop" until it finishes what it's doing.  
HTH

**Comment by pwrose** [comment]
Now using Neo4j on a server, so this is not a problem anymore.
